---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.2
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[hashicorp-vault::default]
  - name: git
    run_list:
      - recipe[apt::default]
      - recipe[yum::default]
      - recipe[hashicorp-vault::default]
    attributes:
      hashicorp-vault:
        installation:
          provider: git
